In [1]:
import numpy as np

### Arrays basics

In [4]:
arr_1 = [1, 2, 3, 4, 5]

#1-d array
np_arr_1 = np.array(arr_1, dtype=np.int8)
np_arr_1

array([1, 2, 3, 4, 5], dtype=int8)

In [5]:
multi_arr = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

#multi dim array here, 2D
np_multi_arr = np.array(multi_arr)
np_multi_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
#Defining the start value, stop value
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
# with start, end and no. of values here, with
# 0 to 5 and 7 values in between
np.linspace(0, 5, 7)

array([0.        , 0.83333333, 1.66666667, 2.5       , 3.33333333,
       4.16666667, 5.        ])

In [9]:
np.zeros(4) # 1D array of zeroes

array([0., 0., 0., 0.])

In [10]:
np.zeros((2, 3)) # 2D 2x3 matrix of zeroes

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.ones((3, 4)) #same thing for ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [190]:
# identity matrix
np.eye(3, 3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [11]:
#find the size -> gives no. of elements in array
np_multi_arr.size

9

In [12]:
np_multi_arr.dtype

dtype('int64')

In [13]:
# random values-> 7 item array from 10 to 50
np.random.randint(10, 50, 7)

array([26, 22, 17, 19, 26, 49, 34])

In [15]:
np.random.randint(10, 50, size=(2, 3)) # multi dim array

array([[22, 49, 33],
       [36, 39, 45]])

### Slicing and indexing basics

In [18]:
#shape of array
multi_arr = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

#multi dim array here, 2D
np_multi_arr = np.array(multi_arr)

np_multi_arr, np_multi_arr.shape

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 (3, 3))

In [19]:
# get element by index
np_multi_arr[0, 2]

3

In [21]:
np_multi_arr.item(0, 2)

3

In [22]:
# get specific indices, the indices list indicates 
# the indices of the values to extract
np.take(np_multi_arr, [0, 2, 4])

array([1, 3, 5])

In [24]:
np_arr_1[3: 5] #use like a normal list

array([4, 5], dtype=int8)

In [25]:
np_arr_1[:4]

array([1, 2, 3, 4], dtype=int8)

In [26]:
# reverse the array
np_arr_1[::-1]

array([5, 4, 3, 2, 1], dtype=int8)

In [27]:
np_multi_arr[:, 0] #first column from all rows

array([1, 4, 7])

In [28]:
#perform comparisons
np_multi_arr[np_multi_arr > 4]

array([5, 6, 7, 8, 9])

In [30]:
#multiple comparisons
np_multi_arr[(np_multi_arr > 4) & (np_multi_arr < 8)]

array([5, 6, 7])

In [32]:
# replace elements at indices 0, 3, 5 with values 2, 2, 2
np.put(np_multi_arr, [0, 3, 5], [2, 2, 2])

In [33]:
np_multi_arr

array([[2, 2, 3],
       [2, 5, 2],
       [7, 8, 9]])

In [34]:
# unique values
np.unique(np_multi_arr)

array([2, 3, 5, 7, 8, 9])

### Reshaping business

In [41]:
# reshape 9x9 array into 9X1 
np_multi_arr = np_multi_arr.reshape((9, 1))
np_multi_arr

array([[2],
       [2],
       [3],
       [2],
       [5],
       [2],
       [7],
       [8],
       [9]])

In [43]:
#shape of array
multi_arr = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

#multi dim array here, 2D
np_multi_arr = np.array(multi_arr)

np_multi_arr, np_multi_arr.shape

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 (3, 3))

In [45]:
np.resize(np_multi_arr, (2, 5)) 
#only returns the value, 
#does not modify the original array

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 1]])

In [46]:
np_multi_arr #still the same. 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
np_multi_arr.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [48]:
np_multi_arr.swapaxes(0, 1 #same as transpose for a 2d array

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [49]:
np_multi_arr.flatten('F')

'''
Parameters
order{‘C’, ‘F’, ‘A’, ‘K’} are optional
‘C’ means to flatten in row-major (C-style) order. 
‘F’ means to flatten in column-major (Fortran- style) order. 
‘A’ means to flatten in column-major order 
if a is Fortran contiguous in memory, row-major order otherwise. 
‘K’ means to flatten a in 
the order the elements occur in memory. The default is ‘C’.
'''

array([1, 4, 7, 2, 5, 8, 3, 6, 9])

In [52]:
np_multi_arr.sort(axis = 1)
np_multi_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Stacking and splitting thingies

In [55]:
arr = np.random.randint(10, size=(2, 3))
arr

array([[4, 2, 6],
       [3, 5, 0]])

In [57]:
arr2 = np.random.randint(10, size=(2, 3))
arr2

array([[4, 0, 2],
       [1, 3, 4]])

In [58]:
# stack horizontally
np.hstack((arr, arr2))

array([[4, 2, 6, 4, 0, 2],
       [3, 5, 0, 1, 3, 4]])

In [59]:
# vertically
np.vstack((arr, arr2))

array([[4, 2, 6],
       [3, 5, 0],
       [4, 0, 2],
       [1, 3, 4]])

In [60]:
# combine arrays
np.column_stack((arr, arr2))

array([[4, 2, 6, 4, 0, 2],
       [3, 5, 0, 1, 3, 4]])

In [61]:
np.row_stack((arr, arr2))

array([[4, 2, 6],
       [3, 5, 0],
       [4, 0, 2],
       [1, 3, 4]])

In [62]:
# Split 3x3 array into 3 arrays
arr = np.random.randint(10, size=(3, 3))
arr

array([[1, 1, 7],
       [6, 5, 4],
       [6, 8, 5]])

In [63]:
np.hsplit(arr, 3) # horizontal split into 3 arrays

[array([[1],
        [6],
        [6]]),
 array([[1],
        [5],
        [8]]),
 array([[7],
        [4],
        [5]])]

In [68]:
# make a 2x10 array
arr = np.random.randint(10, size=(2, 10))

In [69]:
# horizontal split after 1st and 2nd column
arr, np.hsplit(arr, (2,6))

(array([[9, 1, 1, 0, 7, 4, 8, 3, 2, 2],
        [3, 4, 6, 0, 2, 7, 2, 8, 4, 8]]),
 [array([[9, 1],
         [3, 4]]),
  array([[1, 0, 7, 4],
         [6, 0, 2, 7]]),
  array([[8, 3, 2, 2],
         [2, 8, 4, 8]])])

### Math funcs

In [71]:
arr = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

arr, arr2

(array([1, 2, 3, 4, 5]), array([10, 20, 30, 40, 50]))

In [72]:
# add, sub, mul, div
arr + arr2, arr-arr2, arr*arr2, arr/arr2

(array([11, 22, 33, 44, 55]),
 array([ -9, -18, -27, -36, -45]),
 array([ 10,  40,  90, 160, 250]),
 array([0.1, 0.1, 0.1, 0.1, 0.1]))

In [75]:
# multi dim array of 3x3 from 1 to 50
arrm = np.random.randint(1, 50, (3, 3))
arrm

array([[34, 29, 47],
       [ 1, 43,  7],
       [45, 13, 22]])

In [76]:
# a random val from arr
np.random.choice(arr)

4

In [88]:
np.random.seed(13) # seed makes it possible to reproduce random values

In [89]:
np.random.rand(3)

array([0.77770241, 0.23754122, 0.82427853])

In [92]:
np.random.seed(13)
np.random.rand(3)

array([0.77770241, 0.23754122, 0.82427853])

In [94]:
# sum
arr, arr.sum()

(array([1, 2, 3, 4, 5]), 15)

In [95]:
arrm

array([[34, 29, 47],
       [ 1, 43,  7],
       [45, 13, 22]])

In [96]:
arrm.sum(axis = 1) #col wise sum

array([110,  51,  80])

In [97]:
# max and min of rows, col wise
arrm.max(axis = 1), arrm.min(axis = 1)

(array([47, 43, 45]), array([29,  1, 13]))

In [98]:
np.multiply(arr, arr2)

array([ 10,  40,  90, 160, 250])

In [99]:
np.divide(arr, arr2)

array([0.1, 0.1, 0.1, 0.1, 0.1])

In [100]:
# remainder upon division
np.remainder(arr, arr2)

array([1, 2, 3, 4, 5])

In [102]:
arr = np.array([[1, 2], [3, 4]])
arr2 = np.array([[2, 4], [6, 9]])

np.power (arr, arr2) # arr to power arr2

array([[     1,     16],
       [   729, 262144]])

In [103]:
np.sqrt(arr) #square root

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [104]:
np.cbrt(arr) #cube root

array([[1.        , 1.25992105],
       [1.44224957, 1.58740105]])

In [105]:
np.absolute([-2, 0, -5, 90]) #remove signs

array([ 2,  0,  5, 90])

In [106]:
# exp of all items
np.exp(arr)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [107]:
np.log(arr) # log base e 

array([[0.        , 0.69314718],
       [1.09861229, 1.38629436]])

In [108]:
np.log2(arr) # log base 2

array([[0.       , 1.       ],
       [1.5849625, 2.       ]])

In [109]:
np.log10(arr) #log base 10

array([[0.        , 0.30103   ],
       [0.47712125, 0.60205999]])

In [111]:
# greatest common divisor(GCD), Lowest common multiple(LCM)
np.gcd.reduce([9, 12, 15]), np.lcm.reduce([9, 12, 15])

(3, 180)

In [112]:
# round to floor, ceiling

np.floor([1.2, 2.8])

array([1., 2.])

In [113]:
np.ceil([1.2, 2.8])

array([2., 3.])

In [131]:
# argmax --> max value per row
a = np.arange(6).reshape(2,3) + 10
print(a)
np.argmax(a, axis = 0)

[[10 11 12]
 [13 14 15]]


array([1, 1, 1])

In [132]:
np.argmax(a, axis = 1)

array([2, 2])

In [150]:
np.sin(a) #trig functions

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [151]:
np.cos(a), np.tan(a)

(array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
         0.96017029,  0.75390225, -0.14550003, -0.91113026]),
 array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501,
        -0.29100619,  0.87144798, -6.79971146, -0.45231566]))

In [152]:
np.pi #Pi constant

3.141592653589793

In [153]:
np.arcsin(1), np.arccos(1), np.arctan(1)

(1.5707963267948966, 0.0, 0.7853981633974483)

In [154]:
# radian to deg and vice versa
np.rad2deg(np.pi)

180.0

In [156]:
np.deg2rad(180)

3.141592653589793

In [157]:
#hypotenuse func
np.hypot(3, 4)

5.0

### Statistics functions

In [149]:
a = np.arange(1, 10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [143]:
#mean
np.mean(a)

5.0

In [144]:
np.median(a)
#median

5.0

In [145]:
np.average(a)
#average

5.0

In [146]:
np.std(a)
#standard dev

2.581988897471611

In [147]:
np.var(a)
#variance

6.666666666666667

In [148]:
np.percentile(a, 50, axis = 0) #get 50 percentile of a

5.0

### Matrix usecases

In [160]:
arr1 = np.array([2, 3])
arr2 = np.array([3, 2])

#compare functions
np.greater(arr1, arr2)

array([False,  True])

In [162]:
np.less(arr1, arr2)

array([ True, False])

In [163]:
np.greater_equal(arr1, arr2), np.less_equal(arr1, arr2)

(array([False,  True]), array([ True, False]))

In [164]:
np.not_equal(arr1, arr2)

array([ True,  True])

In [165]:
np.equal(arr1, arr2)

array([False, False])

In [166]:
from numpy import linalg as LA

In [175]:
a1 = np.random.randint(1, 5, (2, 2))
a2 = np.random.randint(6, 10, (2, 2))

a1, a2

(array([[4, 4],
        [1, 3]]),
 array([[7, 7],
        [9, 6]]))

In [176]:
np.dot(a1, a2) #dot product

array([[64, 52],
       [34, 25]])

In [179]:
#dot over two or more arrays

a3 = np.random.randint(10, 20, (2, 2))

LA.multi_dot([a1, a2, a3])

array([[1352, 1624],
       [ 692,  826]])

In [180]:
#inner product
np.inner(a1, a2)

array([[56, 60],
       [28, 27]])

In [181]:
#eigenvalues and eigenvectors
LA.eig(a1)

(array([5.56155281, 1.43844719]),
 array([[ 0.93153209, -0.84212294],
        [ 0.36365914,  0.5392856 ]]))

In [182]:
LA.eigvals(a1)

array([5.56155281, 1.43844719])

In [183]:
#vector norm --> sqrt(sum(x**2))
LA.norm(a1)

6.48074069840786

In [184]:
#inverse
LA.inv(a1)

array([[ 0.375, -0.5  ],
       [-0.125,  0.5  ]])

In [185]:
#conditional number
LA.cond(a1)

5.052060979868452

In [187]:
# raise matrix to the power of n
# Given [[a, b], [c, d]]
# [[a² + bc, ab + db], [ac + dc, d² + bc]

LA.matrix_power(a1, 2)

array([[20, 28],
       [ 7, 13]])

In [188]:
# determinant --> det([[a, b], [c, d]]) = a*d - b*c
LA.det(a1)

7.999999999999998

In [189]:
# matrix x its inverse gives identity
np.dot(a1, LA.inv(a1))

array([[1., 0.],
       [0., 1.]])

### Save and load numpy objects


In [192]:
a = np.array([[1, 2], [3, 4]])
np.save('a_array', a) #saves as .npy file on disk

In [193]:
# load 
a1 = np.load('a_array.npy')
a1

array([[1, 2],
       [3, 4]])

In [194]:
# as csv
np.savetxt('a.csv', a)

In [195]:
a2 = np.loadtxt('a.csv')
a2

array([[1., 2.],
       [3., 4.]])

In [ ]:
# or load csv via pandas, mor convenient that way